"""Generate the PyInstaller spec and build dist/PostScheduler.exe."""

import os
import shutil
import subprocess
import sys

APP_NAME = "PostScheduler"
ENTRY_POINT = "main.py"
ROOT = os.path.dirname(os.path.abspath(__file__))
SPEC_PATH = os.path.join(ROOT, APP_NAME + ".spec")

# PyQt modules the app never imports
EXCLUDED_MODULES = [
    "tkinter", "curses", "pydoc_data",
    "PyQt5.QtBluetooth", "PyQt5.QtDBus", "PyQt5.QtDesigner",
    "PyQt5.QtHelp", "PyQt5.QtLocation", "PyQt5.QtMacExtras",
    "PyQt5.QtMultimedia", "PyQt5.QtMultimediaWidgets",
    "PyQt5.QtNetwork", "PyQt5.QtNetworkAuth", "PyQt5.QtNfc",
    "PyQt5.QtOpenGL", "PyQt5.QtPositioning", "PyQt5.QtPrintSupport",
    "PyQt5.QtPurchasing", "PyQt5.QtQml", "PyQt5.QtQuick",
    "PyQt5.QtQuickWidgets", "PyQt5.QtRemoteObjects", "PyQt5.QtSensors",
    "PyQt5.QtSerialPort", "PyQt5.QtSql", "PyQt5.QtSvg", "PyQt5.QtTest",
    "PyQt5.QtTextToSpeech", "PyQt5.QtWebChannel", "PyQt5.QtWebSockets",
    "PyQt5.QtWinExtras", "PyQt5.QtXml", "PyQt5.uic",
]

# unused Qt GL/QML/network dlls and imageformat/platform plugins
DROP_BINARIES = [
    "qt5qml", "qt5quick", "qt5websockets", "qt5network", "qt5svg",
    "opengl32sw", "d3dcompiler_47", "libegl", "libglesv2",
    "qwebgl", "qminimal", "qoffscreen", "qsvg", "qicns", "qtga",
    "qwbmp", "qtiff", "qtuiotouchplugin", "qxdgdesktopportal",
]

SPEC_TEMPLATE = """# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_exe.py - do not edit by hand.
import os
from PyInstaller.utils.hooks import collect_submodules

hiddenimports = collect_submodules('vk_api')

a = Analysis(
    ['%(entry)s'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=%(excludes)s,
    noarchive=False,
    optimize=0,
)

_DROP = %(drop)s
a.binaries = [b for b in a.binaries
              if not any(p in os.path.basename(b[0]).lower() for p in _DROP)]

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='%(name)s',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=%(icon)s,
)
"""


def write_spec() -> None:
    icon = "'icon.ico' if os.path.exists('icon.ico') else None"
    spec = SPEC_TEMPLATE % {
        "entry": ENTRY_POINT,
        "excludes": repr(EXCLUDED_MODULES),
        "drop": repr(DROP_BINARIES),
        "name": APP_NAME,
        "icon": icon,
    }
    with open(SPEC_PATH, "w", encoding="utf-8") as f:
        f.write(spec)


def clean() -> None:
    for path in ("dist", "build"):
        full = os.path.join(ROOT, path)
        if os.path.isdir(full):
            shutil.rmtree(full)


def build() -> int:
    cmd = [sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean", SPEC_PATH]
    result = subprocess.run(cmd, cwd=ROOT)
    if result.returncode != 0:
        print("\nBUILD FAILED, see output above")
        return 1

    exe = os.path.join(ROOT, "dist", APP_NAME + ".exe")
    if not os.path.exists(exe):
        print(f"\nBUILD FAILED: {exe} not found")
        return 1

    size_mb = os.path.getsize(exe) / (1024 * 1024)
    print("\n" + "=" * 50)
    print(f"  Build OK: dist\\{APP_NAME}.exe  ({size_mb:.1f} MB)")
    print("=" * 50)
    return 0


if __name__ == "__main__":
    clean()
    write_spec()
    sys.exit(build())
